# Generated by Django 5.0.3 on 2024-06-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.record'),
        ),
    ]
